apiVersion: v1
kind: ServiceAccount
metadata:
  name: workspace-controller
  namespace: workspace-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/workspace-controller-role

