apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workspace-domain-wildcard-tls
  namespace: workspace-system  # Put it in a central namespace
spec:
  secretName: workspace-domain-wildcard-tls
  issuerRef:
    name: letsencrypt-dns01  # Must be a DNS-01 issuer
    kind: ClusterIssuer
  dnsNames:
  - "*.${REPLACE_ME}"
  - "${REPLACE_ME}"
  